![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
my_array = np.arange(0,10)
print(my_array[9:0:-2])
print(my_array[-1:0:-2])

[9 7 5 3 1]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [18]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [21]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [49]:
my_array_4= np.arange(1,21)
my_matrix=my_array_4.reshape(4,5)
#my_array_4=np.reshape(my_array_4(4,5))
print(my_matrix)
my_matrix = np.flip(my_matrix)
print(my_matrix)
ejr_4 = my_matrix[::-1,::-1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [63]:
my_array_4= np.arange(1,21)
my_matrix=my_array_4.reshape(4,5)
print(my_matrix)

ejr_5 = my_matrix[:2, :2]
#ejr_5 = my_matrix[-1:-3:-1, -1:-3:-1] para la matriz cambiada
print(ejr_5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [4]:
my_array_4= np.arange(1,21)
my_matrix=my_array_4.reshape(4,5)
print(my_matrix)
my_matrix_flip = np.flip(my_matrix)

ejr_6 = my_matrix[0][0],my_matrix[0][2], my_matrix[0][4], my_matrix[2][0],my_matrix[2][2], my_matrix[2][4]
matriz_ejr_6 = np.array(ejr_6).reshape(2,3)
otra = my_matrix_flip[-1::2, -1::2]
otra_2 = my_matrix[::2 , ::2]
print(matriz_ejr_6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [10]:
my_array_4= np.arange(1,21)
my_matrix=my_array_4.reshape(4,5)
print(my_matrix)
my_matrix_flip = np.flip(my_matrix)

ejr_7 = my_matrix[:3, :]
ejr_7 = np.flip(ejr_7, axis=1)
otra = my_matrix_flip[3:0:-1,::]
print(ejr_7)
print(otra)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [108]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
#1
filtro = x == "Loro"
print(x[filtro])
#2
loro = np.where(x == "Loro")
print(x[loro])
# x[np.where(x == "Loro")]
#3
loro = []
for elemento in x:
    if elemento == "Loro":
        loro.append(elemento)

loro = np.array(loro)

print(loro)
#4
loro = np.extract(x == "Loro", x)

print(loro)
#5
x[[True,False,False,True,False ]]

['Loro' 'Loro']
['Loro' 'Loro']
['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [111]:
my_array_4= np.arange(1,21)
my_matrix=my_array_4.reshape(2,5,2)
print(my_matrix)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [115]:
my_array_4= np.arange(1,21)
my_matrix=my_array_4.reshape(4,5)
print(my_matrix)


my_matrix = np.flip(my_matrix)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [124]:

ejr_11 = np.full((10), 0)
# ejr_11 = np.zeros(10)
print(ejr_11)
ejr_11_bytes = ejr_11.nbytes
print(ejr_11_bytes)
ejr_11[3] = 1
print(ejr_11)


[0 0 0 0 0 0 0 0 0 0]
80
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [11]:
vector = np.arange(10, 50)
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [138]:
vector = [1,2,0,0,4,0]
no_zero= np.nonzero(vector)
print(no_zero)
lista = list(no_zero[0])
print(lista)

(array([0, 1, 4]),)
[0, 1, 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [142]:

my_matrix = np.random.randint(60, size = (10,10))
print(my_matrix)
n_max = np.min(my_matrix)
n_min = np.max(my_matrix)
print(f"El número máximo es {n_max} y el mínimo es {n_min}")

[[53 22  9 45 11 32 49 26 50  7]
 [26 34 38  0 56 18  6 53  1 13]
 [26  7 57 19  7  4 24 13 58 52]
 [47 23 24 48 21 39 33 28 30 16]
 [31 40  9  3  2 40 53 53 43  7]
 [33 33 16  8 43 29  0 21 24  3]
 [56 26 28 16 42 55 37  9  8 34]
 [39 44 53 53  9 31  4 10 31 43]
 [28 47 26 49 24  7 44 23 47 14]
 [48 24 38 54 44 28  1 54 54 18]]
El número máximo es 0 y el mínimo es 58


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [146]:

my_matrix = np.random.randint(60, size = 30)
print(my_matrix)
n_media = np.mean(my_matrix)
print(n_media)

[45 53 59 17 25 36 22 14 36 56 43 25 36 27 19 11 33 12  3 19  2 58 31 45
 26 13 27 19 33 53]
29.933333333333334


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [12]:
ejer_16 = np.ones((5,5))
print(ejer_16)
ejer_16[1:4,1:4]= 0
#ejer_16[1:-1, 1:-1]=0 del indice uno al menos uno, que no coge el menos uno 
print(ejer_16)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [188]:
ejer_17 = np.ones([8,8])

for i in range(len(ejer_17)):
    for j in range(len(ejer_17[i])):
        if i % 2 != 0: 
            if j % 2 != 0 :
                ejer_17[i][j] = 0
        elif i % 2 == 0:
            if j % 2 == 0:
                ejer_17[i][j] = 0
    
print(ejer_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [60]:
ejer_17 = np.zeros([8,8])

for i in range(8):
    for j in range(8):
        if (i % 2 == 0 and j % 2 != 0) or (j % 2 == 0 and i % 2 != 0):
            ejer_17[i, j] = 1
print(ejer_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [59]:
ejer_17 = np.ones([8,8])
ejer_17[0::2, 0::2] = 0
ejer_17[1::2, 1::2] = 0
print(ejer_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [62]:
ejer_18 = np.array(([0,1],[1,0]), dtype=float)
np.tile(ejer_18, (4,4))



array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [205]:
my_matrix = np.random.randint(10, size = (5,5))
media = np.mean(my_matrix)
desviacion_std = np.std(my_matrix)
norma = (my_matrix - media)/desviacion_std
print(norma)

[[-0.96507308  1.31104267 -0.50984993  0.40059637 -0.05462678]
 [-1.87551938  0.85581952 -1.42029623  0.40059637  0.85581952]
 [-0.50984993  1.31104267  0.40059637  0.85581952  2.22148897]
 [ 0.40059637 -1.42029623 -0.50984993 -0.05462678 -0.50984993]
 [-0.50984993  1.31104267 -1.42029623 -0.05462678 -0.50984993]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [211]:
vector = np.arange(11)
print(vector)

vector_2 = vector.copy()
vector_2[(vector_2 >= 3) & (vector_2 <= 8)] = -1
print(vector_2)

vector_3 = vector.copy()
vector_3[(vector_3 >= 3) & (vector_3 <= 8)] = False
print(vector_3)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2  0  0  0  0  0  0  9 10]
